#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EET321_Lab5_S16")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEET321_Lab5_Table(EET321_Lab5_Table instance);
    partial void UpdateEET321_Lab5_Table(EET321_Lab5_Table instance);
    partial void DeleteEET321_Lab5_Table(EET321_Lab5_Table instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Lab5.Properties.Settings.Default.EET321_Lab5_S16ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EET321_Lab5_Table> EET321_Lab5_Tables
		{
			get
			{
				return this.GetTable<EET321_Lab5_Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EET321_Lab5_Table")]
	public partial class EET321_Lab5_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _DateTime;
		
		private string _GroupID;
		
		private string _BoardID;
		
		private int _SystemClockFreq;
		
		private int _SampleFrequency;
		
		private string _DataSet;
		
		private float _Measurement;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDateTimeChanging(System.DateTime value);
    partial void OnDateTimeChanged();
    partial void OnGroupIDChanging(string value);
    partial void OnGroupIDChanged();
    partial void OnBoardIDChanging(string value);
    partial void OnBoardIDChanged();
    partial void OnSystemClockFreqChanging(int value);
    partial void OnSystemClockFreqChanged();
    partial void OnSampleFrequencyChanging(int value);
    partial void OnSampleFrequencyChanged();
    partial void OnDataSetChanging(string value);
    partial void OnDataSetChanged();
    partial void OnMeasurementChanging(float value);
    partial void OnMeasurementChanged();
    #endregion
		
		public EET321_Lab5_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="NChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoardID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string BoardID
		{
			get
			{
				return this._BoardID;
			}
			set
			{
				if ((this._BoardID != value))
				{
					this.OnBoardIDChanging(value);
					this.SendPropertyChanging();
					this._BoardID = value;
					this.SendPropertyChanged("BoardID");
					this.OnBoardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemClockFreq", DbType="Int NOT NULL")]
		public int SystemClockFreq
		{
			get
			{
				return this._SystemClockFreq;
			}
			set
			{
				if ((this._SystemClockFreq != value))
				{
					this.OnSystemClockFreqChanging(value);
					this.SendPropertyChanging();
					this._SystemClockFreq = value;
					this.SendPropertyChanged("SystemClockFreq");
					this.OnSystemClockFreqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleFrequency", DbType="Int NOT NULL")]
		public int SampleFrequency
		{
			get
			{
				return this._SampleFrequency;
			}
			set
			{
				if ((this._SampleFrequency != value))
				{
					this.OnSampleFrequencyChanging(value);
					this.SendPropertyChanging();
					this._SampleFrequency = value;
					this.SendPropertyChanged("SampleFrequency");
					this.OnSampleFrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSet", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string DataSet
		{
			get
			{
				return this._DataSet;
			}
			set
			{
				if ((this._DataSet != value))
				{
					this.OnDataSetChanging(value);
					this.SendPropertyChanging();
					this._DataSet = value;
					this.SendPropertyChanged("DataSet");
					this.OnDataSetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Measurement", DbType="Real NOT NULL")]
		public float Measurement
		{
			get
			{
				return this._Measurement;
			}
			set
			{
				if ((this._Measurement != value))
				{
					this.OnMeasurementChanging(value);
					this.SendPropertyChanging();
					this._Measurement = value;
					this.SendPropertyChanged("Measurement");
					this.OnMeasurementChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
